/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type PetInput = {
  customerId: number,
  farmGate?: boolean | null,
  gender?: PetGenders | null,
  species?: Species | null,
  weight?: number | null,
  foodChain?: boolean | null,
  cphNumber?: number | null,
  accountType?: AccountTypes | null,
  active?: boolean | null,
  medication?: boolean | null,
  name?: string | null,
  healthy?: boolean | null,
  medicationNotes?: string | null,
  foodUse?: Array< FoodUse | null > | null,
  pregnant?: boolean | null,
  dob?: string | null,
  healthNotes?: string | null,
  count?: number | null,
  passport?: string | null,
  tags?: string | null,
};

export enum PetGenders {
  MALE = "MALE",
  FEMALE = "FEMALE",
  MIXED = "MIXED",
}


export enum Species {
  CAT = "CAT",
  DOG = "DOG",
  ALPACA = "ALPACA",
  BEARDED_DRAGON = "BEARDED_DRAGON",
  BIRD_OF_PREY = "BIRD_OF_PREY",
  BUDGERIGAR = "BUDGERIGAR",
  CANARY = "CANARY",
  CHICKEN = "CHICKEN",
  CHINCHILLA = "CHINCHILLA",
  COCKATIEL = "COCKATIEL",
  COCKATOO = "COCKATOO",
  COW = "COW",
  DEGU = "DEGU",
  DONKEY = "DONKEY",
  DUCK = "DUCK",
  FERRET = "FERRET",
  FISH = "FISH",
  FOX = "FOX",
  GECKO = "GECKO",
  GERBIL = "GERBIL",
  GOAT = "GOAT",
  GOOSE = "GOOSE",
  GUINEA_PIG = "GUINEA_PIG",
  HAMSTER = "HAMSTER",
  HEDGEHOG = "HEDGEHOG",
  HORSE = "HORSE",
  IGUANA = "IGUANA",
  LLAMA = "LLAMA",
  LOVEBIRD = "LOVEBIRD",
  MOUSE = "MOUSE",
  PARROT = "PARROT",
  PIG = "PIG",
  PIGEON = "PIGEON",
  RABBIT = "RABBIT",
  RAT = "RAT",
  SHEEP = "SHEEP",
  SNAKE = "SNAKE",
  SUGAR_GLIDER = "SUGAR_GLIDER",
  TORTOISE = "TORTOISE",
  TURKEY = "TURKEY",
}


export enum AccountTypes {
  INDIVIDUAL = "INDIVIDUAL",
  GROUP = "GROUP",
}


export enum FoodUse {
  NON_FOOD_USE = "NON_FOOD_USE",
  MEAT = "MEAT",
  MILK = "MILK",
  EGGS = "EGGS",
}


export type Pet = {
  __typename: "Pet",
  uuid: string,
  customerId: number,
  farmGate?: boolean | null,
  gender?: PetGenders | null,
  species?: Species | null,
  weight?: number | null,
  foodChain?: boolean | null,
  cphNumber?: number | null,
  accountType?: AccountTypes | null,
  active?: boolean | null,
  medication?: boolean | null,
  name?: string | null,
  healthy?: boolean | null,
  medicationNotes?: string | null,
  foodUse?: Array< FoodUse | null > | null,
  pregnant?: boolean | null,
  dob?: string | null,
  healthNotes?: string | null,
  count?: number | null,
  passport?: string | null,
  tags?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
};

export type PetSnapshotInput = {
  petUuid: string,
  customerId?: number | null,
  orderId?: number | null,
  quoteItemId?: number | null,
  farmGate?: boolean | null,
  gender?: PetGenders | null,
  species?: Species | null,
  weight?: number | null,
  foodChain?: boolean | null,
  cphNumber?: number | null,
  accountType?: AccountTypes | null,
  active?: boolean | null,
  medication?: boolean | null,
  name?: string | null,
  healthy?: boolean | null,
  medicationNotes?: string | null,
  foodUse?: Array< FoodUse | null > | null,
  pregnant?: boolean | null,
  dob?: string | null,
  healthNotes?: string | null,
  count?: number | null,
  passport?: string | null,
  tags?: string | null,
};

export type PetSnapshot = {
  __typename: "PetSnapshot",
  uuid: string,
  petUuid: string,
  customerId?: number | null,
  orderId?: number | null,
  quoteItemId?: number | null,
  farmGate?: boolean | null,
  gender?: PetGenders | null,
  species?: Species | null,
  weight?: number | null,
  foodChain?: boolean | null,
  cphNumber?: number | null,
  accountType?: AccountTypes | null,
  active?: boolean | null,
  medication?: boolean | null,
  name?: string | null,
  healthy?: boolean | null,
  medicationNotes?: string | null,
  foodUse?: Array< FoodUse | null > | null,
  pregnant?: boolean | null,
  dob?: string | null,
  healthNotes?: string | null,
  count?: number | null,
  passport?: string | null,
  tags?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
};

export type UpdatePetsInput = {
  uuid: string,
  customerId: number,
  farmGate?: boolean | null,
  gender?: PetGenders | null,
  species?: Species | null,
  weight?: number | null,
  foodChain?: boolean | null,
  cphNumber?: number | null,
  accountType?: AccountTypes | null,
  active?: boolean | null,
  medication?: boolean | null,
  name?: string | null,
  healthy?: boolean | null,
  medicationNotes?: string | null,
  foodUse?: Array< FoodUse | null > | null,
  pregnant?: boolean | null,
  dob?: string | null,
  healthNotes?: string | null,
  count?: number | null,
  passport?: string | null,
  tags?: string | null,
};

export type UpdatePetSnapshotInput = {
  uuid: string,
  petUuid: string,
  customerId?: number | null,
  orderId?: number | null,
  quoteItemId?: number | null,
  farmGate?: boolean | null,
  gender?: PetGenders | null,
  species?: Species | null,
  weight?: number | null,
  foodChain?: boolean | null,
  cphNumber?: number | null,
  accountType?: AccountTypes | null,
  active?: boolean | null,
  medication?: boolean | null,
  name?: string | null,
  healthy?: boolean | null,
  medicationNotes?: string | null,
  foodUse?: Array< FoodUse | null > | null,
  pregnant?: boolean | null,
  dob?: string | null,
  healthNotes?: string | null,
  count?: number | null,
  passport?: string | null,
  tags?: string | null,
};

export type AddPetMutationVariables = {
  input?: PetInput | null,
};

export type AddPetMutation = {
  addPet?:  {
    __typename: "Pet",
    uuid: string,
    customerId: number,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null,
};

export type AddPetSnapshotMutationVariables = {
  input?: PetSnapshotInput | null,
};

export type AddPetSnapshotMutation = {
  addPetSnapshot?:  {
    __typename: "PetSnapshot",
    uuid: string,
    petUuid: string,
    customerId?: number | null,
    orderId?: number | null,
    quoteItemId?: number | null,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null,
};

export type DeletePetMutationVariables = {
  customerId: number,
  uuid: string,
};

export type DeletePetMutation = {
  deletePet?:  {
    __typename: "Pet",
    uuid: string,
    customerId: number,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null,
};

export type DeletePetSnapshotMutationVariables = {
  uuid: string,
};

export type DeletePetSnapshotMutation = {
  deletePetSnapshot?:  {
    __typename: "PetSnapshot",
    uuid: string,
    petUuid: string,
    customerId?: number | null,
    orderId?: number | null,
    quoteItemId?: number | null,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null,
};

export type UpdatePetMutationVariables = {
  input?: UpdatePetsInput | null,
};

export type UpdatePetMutation = {
  updatePet?:  {
    __typename: "Pet",
    uuid: string,
    customerId: number,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null,
};

export type UpdatePetSnapshotMutationVariables = {
  input?: UpdatePetSnapshotInput | null,
};

export type UpdatePetSnapshotMutation = {
  updatePetSnapshot?:  {
    __typename: "PetSnapshot",
    uuid: string,
    petUuid: string,
    customerId?: number | null,
    orderId?: number | null,
    quoteItemId?: number | null,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null,
};

export type GetPetQueryVariables = {
  customerId: number,
  uuid: string,
};

export type GetPetQuery = {
  getPet?:  {
    __typename: "Pet",
    uuid: string,
    customerId: number,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null,
};

export type GetPetsQueryVariables = {
  customerId: number,
};

export type GetPetsQuery = {
  getPets?:  Array< {
    __typename: "Pet",
    uuid: string,
    customerId: number,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null > | null,
};

export type GetPetSnapshotQueryVariables = {
  uuid: string,
};

export type GetPetSnapshotQuery = {
  getPetSnapshot?:  {
    __typename: "PetSnapshot",
    uuid: string,
    petUuid: string,
    customerId?: number | null,
    orderId?: number | null,
    quoteItemId?: number | null,
    farmGate?: boolean | null,
    gender?: PetGenders | null,
    species?: Species | null,
    weight?: number | null,
    foodChain?: boolean | null,
    cphNumber?: number | null,
    accountType?: AccountTypes | null,
    active?: boolean | null,
    medication?: boolean | null,
    name?: string | null,
    healthy?: boolean | null,
    medicationNotes?: string | null,
    foodUse?: Array< FoodUse | null > | null,
    pregnant?: boolean | null,
    dob?: string | null,
    healthNotes?: string | null,
    count?: number | null,
    passport?: string | null,
    tags?: string | null,
    createdAt?: string | null,
    updatedAt?: string | null,
  } | null,
};
