// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://hg4issqm2ngabfn2mykpaft5cm.appsync-api.eu-west-2.amazonaws.com/graphql',
          region: 'eu-west-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-p53knze75rcnlb6bidngr3f4jm'
        }
    }
};

export default config;