// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://5qf5obovmfduhdwezsbcndrezq.appsync-api.eu-west-2.amazonaws.com/graphql',
          region: 'eu-west-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-ka4pnpamzrgundijerexs6yc7e'
        }
    }
};

export default config;